name: preview

on:
  schedule:
    - cron: "0 10-14 * * *"
  workflow_dispatch:

env:
  NODE_VERSION: "16.x"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "install, run"
        shell: bash
        run: |
          pushd './'
          npm install
          npm start

          npm run send:telegram
          popd
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
