name: "Send Telegram Message"

on:
  schedule:
    - cron: "0 0-14 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: "install, run"
        shell: bash
        run: |
          pushd './'
          npm install
          npm start

          npm run send:telegram
          popd
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
